VideoclubMVC/Controllers/ArtistasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BaseDatos;
using DAL.modelos;
using Utilidades.LambdaLinq;
using VideoclubMVC.Models;
using Utilidades.Formularios;
using PagedList;

namespace VideoclubMVC.Controllers
{
    [Authorize]
    [AllowAnonymous]
    public class ArtistasController : Controller
    {
        private DBConect db = new DBConect();

        // GET: Artistas
        [HttpGet]
        public ActionResult Index(int? page, int? elements)
        {
            var list = db.Artistas.ToList(); 
            var pageNumber = page ?? 1;
            var elementsPerPage = elements ?? 25;
            // will only contain 25 products max because of the pageSiz;
           
            var onePageOfProducts = list.AsQueryable().ToPagedList(pageNumber, elementsPerPage);
            ViewBag.OnePageOfProducts = onePageOfProducts;
            ViewBag.NumeroElementos = elementsPerPage;

            FiltroArtista filtroResult = new FiltroArtista();
            filtroResult.FormModel = new FormModel(typeof(Artista));
            filtroResult.Artistas = list;
            return View(filtroResult);
        }

        public ActionResult Filtrar(FormCollection form)
        {

            ModeloFiltro<Artista> filtro = new ModeloFiltro<Artista>();
            FiltroArtista filtroResult = new FiltroArtista();
            filtroResult.FormModel = new FormModel(typeof(Artista));
            filtroResult.Artistas = filtro.Filtrar(db.Artistas.Where(xs => true), form);

            return View("Index", filtroResult);

        }

        // GET: Artistas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = db.Artistas.Find(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // GET: Artistas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Artistas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Nombre,Apellidos,FechaNacimiento,FechaFallecimiento,Nacionalidad")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Artistas.Add(artista);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(artista);
        }

        // GET: Artistas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = db.Artistas.Find(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // POST: Artistas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Nombre,Apellidos,FechaNacimiento,FechaFallecimiento,Nacionalidad")] Artista artista)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artista).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(artista);
        }

        // GET: Artistas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artista artista = db.Artistas.Find(id);
            if (artista == null)
            {
                return HttpNotFound();
            }
            return View(artista);
        }

        // POST: Artistas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artista artista = db.Artistas.Find(id);
            db.Artistas.Remove(artista);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VideoclubMVC/Views/Artistas/Create.cshtml
@model DAL.modelos.Artista

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artista</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaFallecimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaFallecimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaFallecimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nacionalidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nacionalidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nacionalidad, "", new { @class = "text-danger" })
            </div>
        </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VideoclubMVC/Views/Artistas/Delete.cshtml
@model DAL.modelos.Artista

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Artista</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFallecimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFallecimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nacionalidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nacionalidad)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VideoclubMVC/Views/Artistas/Details.cshtml
@model DAL.modelos.Artista

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Artista</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFallecimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFallecimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nacionalidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nacionalidad)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VideoclubMVC/Views/Artistas/Edit.cshtml
@model DAL.modelos.Artista

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artista</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaFallecimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaFallecimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaFallecimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nacionalidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nacionalidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nacionalidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VideoclubMVC/Views/Artistas/Index.cshtml
@model  VideoclubMVC.Models.FiltroArtista
@{
    ViewBag.Title = "Index";
}

@using PagedList.Mvc; 
@using PagedList;

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>Index</h2>
<div>
    <h2>Filtro</h2>
    <button class="btn btn-primary boton-mostrar-filtros" onclick="ocultarFiltro();">Mostrar</button>
    <div class="form-filtrar">
        @using (Html.BeginForm("Filtrar", "Artistas", FormMethod.Post))
        {
            <div class="form-horizontal">
                <hr />
                <!-- Carga los Inputs de los forms-->
                @Html.Partial("_FormFiltro", Model.FormModel)
            </div>
        }
    </div>

</div>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        @for (int i = 1; i < Model.FormModel.claves.Count; i++)
        {
            <th>
                @Model.FormModel.claves[i]
            </th>
        }
        <th></th>
    </tr>
    
@foreach (var item in ViewBag.OnePageOfProducts) {
    <tr>
        <td>
            
            @item.Nombre
        </td>
        <td>
            @item.Apellidos
        </td>
        <td>
           @item.FechaNacimiento
        </td>
        <td>
            @item.FechaFallecimiento
        </td>
        <td>
            @item.Nacionalidad
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>
@Html.PagedListPager((IPagedList)ViewBag.OnePageOfProducts, page => Url.Action("Index", new { page, elements = ViewBag.NumeroElementos }))

<select id="TypeOfUser" name="typeOfUser" value="Num Elementos"class="active text-normal"
        onchange="doIt(this,'@Url.Action("Index", "Artistas")')">
    <option value="@ViewBag.NumeroElementos">@ViewBag.NumeroElementos</option>
    <option value="5">5</option>
    <option value="10">10</option>
    <option value="25">25</option>
    <option value="50">50</option>
</select>

<script>
    function doIt(item, baseUrl) {
        if (item.value != "") {
            window.location.href = baseUrl + '?page=1&elements=' + item.value + '';
        }
        
    }
</script>