VideoclubMVC/Controllers/PeliculasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BaseDatos;
using DAL.modelos;
using VideoclubMVC.Models;
using Utilidades.LambdaLinq;
using Utilidades.Formularios;

namespace VideoclubMVC.Controllers
{
    public class PeliculasController : Controller
    {
        private DBConect db = new DBConect();

        // GET: Peliculas
        public ActionResult Index()
        {
            FiltroPelicula filtro = new FiltroPelicula();
            filtro.FormModel = new FormModel(typeof(Pelicula));
            filtro.Peliculas = db.Peliculas.ToList();
           
            return View(filtro);
        }


        public ActionResult Filtrar(FormCollection form)
        {
            
            ModeloFiltro<Pelicula> filtro = new ModeloFiltro<Pelicula>();
            FiltroPelicula filtroResult = new FiltroPelicula();
            filtroResult.FormModel = new FormModel(typeof(Pelicula));
            filtroResult.Peliculas = filtro.Filtrar(db.Peliculas.Where(xs => true), form);

            return View("Index", filtroResult);
            
        }

        // GET: Peliculas/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.Peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // GET: Peliculas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Peliculas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPelicula,Titulo,FechaEstreno,Duracion,Genero,Nacionalidad,Nota,Sinopsios")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                pelicula.IdPelicula = Guid.NewGuid();
                db.Peliculas.Add(pelicula);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pelicula);
        }

        // GET: Peliculas/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.Peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPelicula,Titulo,FechaEstreno,Duracion,Genero,Nacionalidad,Nota,Sinopsios")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pelicula).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pelicula);
        }

        // GET: Peliculas/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.Peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Pelicula pelicula = db.Peliculas.Find(id);
            db.Peliculas.Remove(pelicula);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VideoclubMVC/Views/Peliculas/Create.cshtml
@model DAL.modelos.Pelicula

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pelicula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaEstreno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaEstreno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaEstreno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Genero, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nacionalidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nacionalidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nacionalidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sinopsios, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sinopsios, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sinopsios, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VideoclubMVC/Views/Peliculas/Delete.cshtml
@model DAL.modelos.Pelicula

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaEstreno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEstreno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duracion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duracion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nacionalidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nacionalidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sinopsios)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinopsios)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VideoclubMVC/Views/Peliculas/Details.cshtml
@model DAL.modelos.Pelicula

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaEstreno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEstreno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duracion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duracion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nacionalidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nacionalidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sinopsios)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinopsios)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdPelicula }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VideoclubMVC/Views/Peliculas/Edit.cshtml
@model DAL.modelos.Pelicula

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pelicula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdPelicula)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaEstreno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaEstreno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaEstreno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Genero, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nacionalidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nacionalidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nacionalidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sinopsios, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sinopsios, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sinopsios, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VideoclubMVC/Views/Peliculas/Index.cshtml
@model  VideoclubMVC.Models.FiltroPelicula

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div>
    <h2>Filtro</h2>
    <button class="btn btn-primary boton-mostrar-filtros" onclick="ocultarFiltro();">Mostrar</button>
    <div class="form-filtrar">
        @using (Html.BeginForm("Filtrar", "Peliculas", FormMethod.Post))
        {
            <div class="form-horizontal">
                <hr/>
                <!-- Carga los Inputs de los forms-->
                @Html.Partial("_FormFiltro", Model.FormModel)
            </div>
        }
    </div>
   
    </div>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        @for (int i = 1; i < Model.FormModel.claves.Count; i++)
        {
            <th>
                @Model.FormModel.claves[i]
            </th>
        }
        <th></th>
    </tr>

@foreach (var item in Model.Peliculas) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaEstreno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duracion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genero)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nacionalidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nota)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sinopsios)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdPelicula }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdPelicula }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdPelicula })
        </td>
    </tr>
}

</table>